In [1]:
import pandas as pd
import flair
from bpemb import BPEmb
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.spatial.distance import cdist
from sklearn.decomposition import TruncatedSVD
#import spacy

/home/londogard/miniconda3/envs/flair/lib/python3.9/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370151529/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [2]:
full_files_assignment = [f"data/assignment/{x}/assignment.txt" for x in os.listdir('data/assignment')]
full_files_data_assignment = [open(x).read() for x in full_files_assignment if not 'annot' in x and not '.DS' in x]

In [3]:
full_files = [f"data/resumes/{x}" for x in os.listdir('data/resumes')]
full_files_data = [open(x).read() for x in full_files]

full_files_data[0][:500]

'•\nMAALINI KALYANASUNDARAN\n\n#23-03, 7 Alexandra View, Singapore, 158741.\n+65 9186 4989\nmaal89@gmail.com\n\nA highly motivated individual with experience in financial due diligence and auditing of various industries including\nlisted and multinational companies. Competent in providing professional advice in areas such as accounting and\ninternal control systems. Able to work with all members of staff and maintain a professional relationship with the\nclient. Outspoken team player and enjoys a fast-pace'

In [20]:
vectorizer = TfidfVectorizer(stop_words='english', max_df=0.50, min_df=10)
X = vectorizer.fit_transform(full_files_data+full_files_data_assignment)

In [21]:
X_assignment = X[1037:]
X_resume= X[:1037]

In [22]:
dists = cdist(X_assignment[0].toarray(), X_resume.toarray(), metric='cosine')[0]
idx = dists.argpartition(5)[:5]

In [23]:
idx

array([834, 485, 564, 673, 736])

In [30]:
full_files_data[564][:500]

'CHEW JIEN HOONG\nMobile no: +65-9731 0220\njienhoong_chew@hotmail.com\nSingaporean PR\n\n» INTRODUCTION\nA dynamic professional that is seeking a challenging position that leverages on technical, management\nand communication skills gained from exposure in the Big Four accounting firms. Able to adapt quickly\nto solve problems and provide value-adding solutions to contribute to business growth. Driven to\nconstantly update skillset to remain relevant in the industry.\n\n» WORK EXPERIENCE\nManager (Assurance'

In [9]:
svd = TruncatedSVD(n_components=100)

In [10]:
X2=svd.fit_transform(X)

In [11]:
X_assignment = X2[1037:]
X_resume= X2[:1037]

In [13]:
X_assignment.shape

(57, 100)

In [17]:
dists = cdist(X_assignment[:1], X_resume, metric='cosine')[0]
idx = dists.argpartition(5)[:5]

In [18]:
idx

array([636, 803, 834, 411, 564])

In [19]:
dists[idx]

array([0.86881592, 0.86767579, 0.85027917, 0.87312369, 0.87404793])

In [141]:
full_files[485]

'data/resumes/621.txt'

In [142]:
#full_files_data_assignment[0]

In [118]:
dists[1:10]

array([0.92283825, 0.93954975, 0.91325684, 0.90734625, 0.9425231 ,
       0.95441858, 0.96513921, 0.93029642, 0.92184885])